### ISSUE TITLE
prevent item/entity duplication

### ISSUE THREAD

**Issue by ryantheleach** [mikeprimm/SlowSaveAll#1]
If this is saving chunks over multiple ticks, how do you handle entities crossing save boundaries / hopperclocks running over save boundaries in order to duplicate items? Or do these issues just never crop up to any serious degree?

I had thought about tackling this problem, but I lacked the skills to do so, my imagined thought was to split saving into "islands" of loaded chunks, and then save each island by flood-filling to find all the chunks that need saving on each island.

Issues I predicted that would need solving were 
1. portals. allowing items/entities to teleport from one world to the next results in a link between islands, if all chunks end up connected to each other you end up with 1 giant continent instead of smaller islands.
2. region files, if you save the chunks in a given region file, if the region file spans across islands, you would need to merge the islands.
3. while saving any extra chunks that are loaded or unloaded cause the islands to be in flux over the save period, some way of dealing with this would be needed.

**Comment by mikeprimm** [comment]
I don't, any more than the normal saves (other than save-all) from vanilla do.   The window is only during the save itself - SlowSave does the equivalent of a save-all, but just doesn't do it in one tick.  Just like vanilla, if you get a crash without an orderly shutdown, some chunks are going to be more out-of-date than others.  As chunks are not saved as a single transaction with vanilla (other than save-all and an orderly shutdown), the results are the same if a crash were to happen in the middle of a slow save.
